name: Build and Publish Package to Github Packages

# Events that trigger the workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:      

# Environment variables
env:
  NODE_VERSION: '16.x'
  SCOPE: '@ull-tfg'

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      # Checkout of the repository
      - uses: actions/checkout@v3
      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Install dependencies
      - run: yarn install
      # Run tests
      #- run: yarn test
      # Build package
      - run: yarn build
      # Checkout of the repository
      #- uses: actions/checkout@v3
      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: ${{ env.SCOPE }}
      - run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}