name: Build and Publish Package to Github Packages

# Action triggered when pushing in 'main' branch
on:
  push:
    branches:
      - main
  workflow_dispatch:      

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      # Checkout of the repository
      - uses: actions/checkout@v3
      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      # Install dependencies
      - run: yarn install
      # Run tests
      #- run: yarn test
      # Build package
      - run: yarn build
  publish-package:
    needs: build-artifact
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # Checkout of the repository
      - uses: actions/checkout@v3
      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@ull-tfg'
      - run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}